site_name: LoRa Server documentation
repo_url: https://github.com/brocaar/loraserver
theme_dir: docs/material

pages:
  - index.md
  - getting-started.md
  - activating-nodes.md
  - receiving-data.md
  - sending-data.md
  - network-controller.md
  - api.md
  - configuration.md
  - frequently-asked-questions.md
  - changelog.md

extra:
  version: '0.9.0'
  github:
    download_release: true

markdown_extensions:
  - admonition
  - codehilite(css_class=code)

google_analytics: ['UA-3512995-9', 'docs.loraserver.io']
