site_name: LoRa Server documentation
pages:
  - index.md
  - getting-started.md
  - activating-nodes.md
  - receiving-data.md
  - sending-data.md
  - configuration.md
  - api.md
  - changelog.md
theme: readthedocs
repo_url: https://github.com/brocaar/loraserver/
